#!/bin/bash

if [[ "$(uname -s)" = "Darwin" ]]; then
  git config --global user.name 'Timothy Clem'
  git config --global user.email 'timothy.clem@gmail.com'
  git config --global github.user 'tclem'
  git config --global credential.helper osxkeychain
fi

git config --global alias.co checkout
git config --global alias.lo 'log --oneline --decorate'
git config --global alias.lol 'log --oneline --graph --decorate'
git config --global alias.last 'log -1 HEAD'
git config --global alias.first 'git log --reverse --pretty=format:"%h %ad%x09%an%x09%s" --date=short | grep Clem | head -1'

git config --global pull.rebase true
git config --global push.default simple
