#!/bin/bash
#
# macOS specific bootstrap

# Fast keyrepeat
defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

# Disable Accent Menu when you hold down a key
defaults write -g ApplePressAndHoldEnabled -bool false

# Hide desktop icons
defaults write com.apple.finder CreateDesktop false; killall Finder

# Dock on the right
defaults write com.apple.dock autohide -int 1; defaults write com.apple.dock orientation -string right; killall Dock

# iTerm2 will load settings from a shared directory
# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.dotfiles/iterm2"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Set some basic security settings.
defaults write com.apple.Safari \
  com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled \
  -bool false
defaults write com.apple.Safari \
  com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles \
  -bool false
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist 2>/dev/null
sudo defaults write /Library/Preferences/com.apple.loginwindow \
    LoginwindowText \
    "Found this computer? Please contact $(id -F) at $(git config --global user.email)."

# Install Homebrew
bash -c '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

# Use the new zshrc to brew bundle
zsh -c 'brew bundle'

# Fix zsh compaudit issues:
zsh -c 'compaudit | xargs chmod g-w'

# Enable font smoothing for external displays
defaults write -g CGFontRenderingFontSmoothingDisabled -bool FALSE

# Fonts I like: Hasklig, Meslo, SF Mono

# Setup osxkeychain for pushing to https with a personal access token
# printf "protocol=https\\nhost=github.com\\n" | git credential-osxkeychain erase
# printf "protocol=https\\nhost=github.com\\nusername=%s\\npassword=%s\\n" \
#       "$(whoami)" "$GITHUB_TOKEN" \
#       | git credential-osxkeychain store

# VSCode Vim
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
defaults delete -g ApplePressAndHoldEnabled
