#!/bin/bash

# General editor setup
apm install \
  align-regexp \
  atom-beautify \
  atom-ide-ui \
  editor-settings \
  file-icons \
  hyperclick \
  minimap \
  sort-lines \
  teletype \
  vim-mode-plus \
  vim-mode-plus-keymaps-for-surround \

# Haskell hacking
apm install \
  language-haskell \
  ide-haskell-hie \

# Link in editor and package settings
if [ -f ~/.atom/config.cson ]; then
  rm ~/.atom/config.cson
fi
ln -s "$(pwd)/atom/config.cson" ~/.atom/config.cson
