export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export PATH="/usr/local/bin:$ZSH/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH" # Rust cargo
export PATH="$HOME/.local/bin:$PATH" # stack
export PATH="$HOME/.ghcup/bin:$PATH" # ghcup
export PATH="$HOME/.cabal/bin:$PATH" # cabal
export PATH=":bin:$PATH"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/python@3.9/libexec/bin:$PATH"
